const CatsRaces = [
  { value: "srd", label: "sem Raça Definida" },
  { value: "abissinio", label: "Abissínio" },
  { value: "angora_turco", label: "Angorá turco" },
  { value: "asiatico_de_pelo_semi_long", label: "Asiático de Pelo Semi-Longo" },
  { value: "azul_russo", label: "Azul Russo" },
  { value: "balines", label: "Balinês" },
  { value: "bambino", label: "Bambino" },
  { value: "bicolor_oriental", label: "Bicolor Oriental" },
  { value: "bobtail_americano", label: "Bobtail americano" },
  { value: "bobtail_japones", label: "Bobtail japonês" },
  { value: "bombaim", label: "Bombaim" },
  { value: "burmes", label: "Burmês" },
  { value: "burmila", label: "Burmila" },
  { value: "california_spangled", label: "California Spangled" },
  { value: "cingapura", label: "Cingapura" },
  { value: "chartreux", label: "Chartreux" },
  { value: "chausie", label: "Chausie" },
  { value: "colorpoint_de_pelo_curto", label: "Colorpoint de pelo curto" },
  { value: "cornish_rex", label: "Cornish Rex" },
  { value: "curl_americano", label: "Curl Americano" },
  { value: "devon_rex", label: "Devon Rex" },
  { value: "donskoy", label: "Donskoy" },
  { value: "dragon_li", label: "Dragon Li" },
  { value: "egeu", label: "Egeu" },
  { value: "gato_de_bengala", label: "Gato-de-Bengala" },
  { value: "gato_do_chipre", label: "Gato do Chipre" },
  { value: "exotico", label: "Exótico" },
  { value: "gato_asiatico", label: "Gato asiático" },
  { value: "gato_siberiano", label: "Gato Siberiano" },
  { value: "havana_marrom", label: "Havana marrom" },
  { value: "himalaio", label: "Himalaio" },
  { value: "javanes", label: "Javanês" },
  { value: "korat", label: "Korat" },
  { value: "khao_manee", label: "Khao Manee" },
  { value: "kurilian_bobtail", label: "Kurilian Bobtail" },
  { value: "laperml", label: "LaPerml" },
  { value: "levkoy_ucraniano", label: "Levkoy ucraniano" },
  { value: "lykoi", label: "Lykoi" },
  { value: "maine_coon", label: "Maine Coon" },
  { value: "manx", label: "Manx" },
  { value: "manx_de_pelo_longo", label: "Manx de pelo longo" },
  { value: "mau_arabe", label: "Mau Árabe" },
  { value: "mau_egipcio", label: "Mau egípcio" },
  { value: "minskin", label: "Minskin" },
  { value: "mist_australiano", label: "Mist Australiano" },
  { value: "munchkin", label: "Munchkin" },
  { value: "nebelung", label: "Nebelung" },
  { value: "noruegues_da_floresta", label: "Norueguês da Floresta" },
  { value: "ocicat", label: "Ocicat" },
  { value: "ojos_azules", label: "Ojos Azules" },
  { value: "oregon_rex", label: "Oregon Rex" },
  { value: "pelo_curto_americano", label: "Pelo curto americano" },
  { value: "pelo_curto_brasileiro", label: "Pelo curto brasileiro" },
  { value: "pelo_curto_europeu", label: "Pelo curto Europeu" },
  { value: "pelo_curto_ingles", label: "Pelo curto inglês" },
  { value: "pelo_longo_ingles", label: "Pelo longo Inglês" },
  { value: "pelo_curto_oriental", label: "Pelo curto Oriental" },
  { value: "pelo_longo_oriental", label: "Pelo longo Oriental" },
  { value: "persa", label: "Persa" },
  { value: "peterbald", label: "Peterbald" },
  { value: "pixie_bob", label: "Pixie-bob" },
  { value: "raas", label: "Raas" },
  { value: "ragamuffin", label: "Ragamuffin" },
  { value: "ragdoll", label: "Ragdoll" },
  { value: "rex_alemao", label: "Rex Alemão" },
  { value: "sagrado_da_birmania", label: "Sagrado da Birmânia" },
  { value: "savannah", label: "Savannah" },
  { value: "scottish_fold", label: "Scottish Fold" },
  { value: "selkirk_rex", label: "Selkirk Rex" },
  { value: "serengeti", label: "Serengeti" },
  { value: "siames", label: "Siamês" },
  { value: "singapura", label: "Singapura" },
  { value: "snowshoe", label: "Snowshoe" },
  { value: "sokoke", label: "Sokoke" },
  { value: "somali", label: "Somali" },
  { value: "sphynx", label: "Sphynx" },
  { value: "suphalak", label: "Suphalak" },
  { value: "thai", label: "Thai" },
  { value: "tiffany_chantilly", label: "Tiffany-Chantilly" },
  { value: "tonquines", label: "Tonquinês" },
  { value: "toyger", label: "Toyger" },
  { value: "van_turco", label: "Van Turco" },
  { value: "wirehair_americano", label: "Wirehair Americano" },
];

export default CatsRaces;
